[package]
name = "pwrs"
version = "1.1.0"
edition = "2018"
authors = ["Richo Healey <richo@psych0tik.net>"]
license = "MIT"
repository = "https://github.com/richo/pwrs"
description = "a pwgen like utility that generates passphrases"

[dependencies]

rand = "0.7.0"
getopts = "0.2.19"
