[package]
name = "pwrs"
version = "2.0.0"
edition = "2018"
authors = ["Richo Healey <richo@psych0tik.net>"]
license = "MIT"
repository = "https://github.com/richo/pwrs"
description = "a pwgen like utility that generates passphrases"

[dependencies]

rand = "0.9.2"
getopts = "0.2.23"
